### ISSUE TITLE
there are some problems

### ISSUE THREAD

**Issue by populus1430** [bryanculver/minimal-jekyll#1]
Because lack of some flies,the page build failure with the following error:The tag `css` on line 10 in `_includes/head.html,` is not a recognized Liquid tag.The tag `main` on line 10 in `/_layouts/wrapper.html` is not a recognized Liquid tag. The lacking files is https://github.com/orderedlist/minimal(javascripts,stylesheets)
![image](https://user-images.githubusercontent.com/30656778/28952047-568248ee-7901-11e7-852a-2b42afe5a305.png)

**Comment by bryanculver** [comment]
Are you using native Jekyll or Github Pages to build these?

**Comment by populus1430** [comment]
yeah,but  i  used windows platform.When i download  the files from orderedlist,the problems were solved. So I think the problem is the lack of documentation.

**Comment by bryanculver** [comment]
OK because this theme differs from the Material theme. Those tags come from the `jekyll-assets` gem.

**Comment by populus1430** [comment]
Anyway,thank you very much.
